package com.threegroup.tobedated

import com.threegroup.tobedated.generic.AgeRange

data class UserModel(
    var name            : String = "",
    var birthday        : String = "",
    var pronoun         : String = "",
    var gender          : String = "",
    var height          : String = "",
    var ethnicity       : String = "",
    var star            : String = "",
    var sexOrientation  : String = "",
    var seeking         : String = "",
    var sex             : String = "",
    var testResultsMbti : String = "Not Taken",
    var testResultTbd   : Int = 10,
    var children        : String = "",
    var family          : String = "",
    var education       : String = "",
    var religion        : String = "",
    var politics        : String = "",
    var relationship    : String = "",
    var intentions      : String = "",
    var drink           : String = "",
    var smoke           : String = "",
    var weed            : String = "",
    var meetUp          : String = "",
    var promptQ1        : String = "",
    var promptA1        : String = "",
    var promptQ2        : String = "",
    var promptA2        : String = "",
    var promptQ3        : String = "",
    var promptA3        : String = "",
    var bio             : String = "",
    var image1          : String = "",
    var image2          : String = "",
    var image3          : String = "",
    var image4          : String = "",
    var location        : String = "3.0/3.0",
    var status          : Long = 0,
    var number          : String = "",
    var verified        : Boolean = false,
    var seeMe           : Boolean = false,
    var hasThree        : Boolean = false,
    var userPref        : UserSearchPreferenceModel = UserSearchPreferenceModel(),
    var hasCasual       : Boolean = false,
    var hasFriends      : Boolean = false,
    var hasThreeCasual  : Boolean = false,
    var casualAdditions : CasualAdditions = CasualAdditions()
)
data class CasualAdditions(
    var leaning             : String = "",
    var lookingFor          : String = "",
    var experience          : String = "",
    var location            : String = "",
    var comm                : String = "",
    var sexHealth           : String = "",
    var afterCare           : String = "",
    var casualBio           : String = "",
    var promptQ1            : String = "",
    var promptA1            : String = "",
    var promptQ2            : String = "",
    var promptA2            : String = "",
    var promptQ3            : String = "",
    var promptA3            : String = "",

)
data class UserSearchPreferenceModel(
    var ageRange            : AgeRange = AgeRange(18, 35),
    var maxDistance         : Int = 25,
    var gender              : List<String> = listOf("Doesn't Matter"),
    var zodiac              : List<String> = listOf("Doesn't Matter"),
    var sexualOri           : List<String> = listOf("Doesn't Matter"),
    var mbti                : List<String> = listOf("Doesn't Matter"),
    var children            : List<String> = listOf("Doesn't Matter"),
    var familyPlans         : List<String> = listOf("Doesn't Matter"),
    var education           : List<String> = listOf("Doesn't Matter"),
    var religion            : List<String> = listOf("Doesn't Matter"),
    var politicalViews      : List<String> = listOf("Doesn't Matter"),
    var relationshipType    : List<String> = listOf("Doesn't Matter"),
    var intentions          : List<String> = listOf("Doesn't Matter"),
    var drink               : List<String> = listOf("Doesn't Matter"),
    var smoke               : List<String> = listOf("Doesn't Matter"),
    var weed                : List<String> = listOf("Doesn't Matter"),
    var meetUp                : List<String> = listOf("Doesn't Matter"),

    var leaning             :List<String> = listOf("Doesn't Matter"),
    var lookingFor          :List<String> = listOf("Doesn't Matter"),
    var experience          :List<String> = listOf("Doesn't Matter"),
    var location            :List<String> = listOf("Doesn't Matter"),
    var comm                :List<String> = listOf("Doesn't Matter"),
    var sexHealth           :List<String> = listOf("Doesn't Matter"),
    var afterCare           :List<String> = listOf("Doesn't Matter"),
)
