package com.threegroup.tobedated.casual

val preferencesAndDesiresAnswers = listOf(
    listOf(
        "Taking charge and leading in the bedroom comes naturally to me; I enjoy setting the pace and exploring my partner's desires.",
        "While I'm comfortable taking the lead, I also find it thrilling to relinquish control and let my partner take charge for a change.",
        "I prefer a dynamic where both partners take turns leading in the bedroom, creating a balanced and mutually satisfying experience.",
        "I'm open to both scenarios; whether I'm leading or following, what matters most is the connection and chemistry with my partner.",
        "I enjoy a mix of assertiveness and submission in the bedroom, adapting to the moment and my partner's desires.",
        "I'm a firm believer in communication and collaboration; discussing preferences and taking turns leading ensures a fulfilling sexual experience.",
        "Taking charge or letting my partner lead depends on the mood and dynamic between us; flexibility and adaptability keep things exciting.",
        "I appreciate the excitement of taking charge in the bedroom, but I also value the intimacy of allowing my partner to lead.",
        "I enjoy the anticipation of not knowing who will take control in the bedroom; it adds an element of surprise and excitement to our encounters.",
        "I'm comfortable with both roles in the bedroom, as long as there's mutual respect and understanding between partners."
    ),
    listOf(
        "I'm always eager to explore new fantasies and kinks with a willing partner; experimentation keeps things exciting and fosters intimacy.",
        "While I appreciate familiar activities, I'm open to exploring new fantasies and kinks that intrigue me and my partner.",
        "Exploring new fantasies and kinks is essential for keeping the spark alive in a relationship; I'm always open to trying new things.",
        "I believe there's value in both familiar activities and exploring new fantasies and kinks; striking a balance ensures a fulfilling sexual experience.",
        "I enjoy the thrill of discovering new fantasies and kinks with a partner who shares my adventurous spirit and curiosity.",
        "Experimenting with new fantasies and kinks can deepen the connection between partners and enhance sexual satisfaction; I'm all for it.",
        "While I enjoy familiar activities, I'm open to exploring new fantasies and kinks if they align with my interests and comfort level.",
        "I view experimentation as an exciting opportunity for growth and discovery in a relationship; I'm enthusiastic about trying new things with my partner.",
        "I believe in pushing boundaries and expanding my sexual horizons through exploration; trying new fantasies and kinks is an integral part of that journey.",
        "Exploring new fantasies and kinks can lead to exciting discoveries and deepen intimacy between partners; I'm eager to embark on that exploration."
    ),
    listOf(
        "Physical attraction plays a significant role in a sexual encounter for me; it ignites desire and enhances the overall experience.",
        "While physical attraction is important, I also value emotional connection and chemistry in a sexual encounter; it creates a deeper sense of intimacy.",
        "Physical attraction is essential for sparking initial interest, but emotional connection and compatibility are equally important for a fulfilling sexual encounter.",
        "I believe physical attraction sets the stage for a sexual encounter, but genuine connection and mutual respect are what make it truly satisfying.",
        "Physical attraction is a key component of sexual chemistry, but it's the mental and emotional connection that sustains and deepens the encounter for me.",
        "While physical attraction is important, I prioritize compatibility and shared values in a sexual encounter; they contribute to a more meaningful and satisfying experience.",
        "Physical attraction is just one aspect of a fulfilling sexual encounter; mutual respect, communication, and shared desires are equally important to me.",
        "While physical attraction can spark initial interest, it's emotional connection and compatibility that keep me engaged and fulfilled in a sexual encounter.",
        "Physical attraction is important, but it's the connection and chemistry between partners that truly elevate the sexual experience for me.",
        "While physical attraction is undeniable, I believe genuine connection and mutual understanding are what make a sexual encounter truly memorable and fulfilling."
    ),
    listOf(
        "I enjoy engaging in foreplay and building anticipation; it enhances the intimacy and excitement of the main event.",
        "Foreplay is an essential part of a sexual encounter for me; it builds anticipation and heightens pleasure for both partners.",
        "I appreciate the buildup of foreplay and the anticipation it creates; it sets the stage for a more enjoyable and satisfying main event.",
        "Foreplay is crucial for me; it allows me to connect with my partner on a deeper level and ensures a more fulfilling sexual experience.",
        "While I enjoy the main event, I also value the intimacy and connection that comes from engaging in foreplay with my partner.",
        "Foreplay is an integral part of a sexual encounter for me; it's where the magic happens and sets the tone for an unforgettable experience.",
        "I find foreplay to be incredibly arousing and enjoyable; it's an essential precursor to the main event and enhances the overall experience.",
        "Foreplay is essential for building anticipation and increasing arousal; it's a key component of a satisfying sexual encounter for me.",
        "I prefer to take my time with foreplay and savor each moment; it adds depth and intensity to the main event.",
        "Foreplay is not just a prelude to the main event for me; it's an integral part of the sexual experience that I value and prioritize."
    ),
    listOf(
        "Open communication about sexual boundaries and preferences is crucial for me; it ensures a mutually satisfying and respectful encounter.",
        "I believe discussing sexual boundaries and preferences beforehand is essential for creating a safe and enjoyable experience for both partners.",
        "I'm comfortable discussing my sexual boundaries and preferences with my partner; it promotes trust, understanding, and mutual satisfaction.",
        "Having open and honest conversations about sexual boundaries and preferences is important to me; it helps ensure a pleasurable and fulfilling encounter.",
        "I prioritize discussing sexual boundaries and preferences with my partner before engaging in any sexual activity; it fosters trust and respect.",
        "I believe in clear and open communication about sexual boundaries and preferences; it sets the stage for a more enjoyable and satisfying encounter.",
        "I'm proactive about discussing sexual boundaries and preferences with my partner; it's a crucial step in ensuring both of our needs are met.",
        "I'm comfortable expressing my sexual boundaries and preferences with my partner; it's a necessary part of building trust and intimacy in a relationship.",
        "I value open dialogue about sexual boundaries and preferences; it allows for a deeper understanding and connection between partners.",
        "Discussing sexual boundaries and preferences with my partner is non-negotiable for me; it's essential for a fulfilling and respectful sexual encounter."
    ),
    listOf(
        "I enjoy a slow and sensual pace during sex; it allows for deeper connection and intimacy with my partner.",
        "While I appreciate a slow and sensual pace, I also enjoy the intensity and passion of a more fast-paced encounter.",
        "I prefer a slow and sensual pace during sex; it heightens the pleasure and allows me to savor each moment with my partner.",
        "A slow and sensual pace during sex is my preference; it allows for exploration, connection, and mutual pleasure.",
        "I find a slow and sensual pace during sex to be incredibly arousing and satisfying; it deepens the intimacy and enhances the experience.",
        "I enjoy the contrast between slow, sensual moments and intense, passionate bursts of energy during sex; it keeps things exciting and dynamic.",
        "A slow and sensual pace during sex is essential for me; it allows me to fully immerse myself in the experience and connect with my partner on a deeper level.",
        "I appreciate the buildup and anticipation that comes with a slow and sensual pace during sex; it creates a more fulfilling and memorable encounter.",
        "I prefer a slow and sensual pace during sex; it allows me to be fully present and attentive to my partner's needs and desires.",
        "While I enjoy a slow and sensual pace, I'm also open to exploring different rhythms and intensities with my partner to find what feels most pleasurable for both of us."
    ),
    listOf(
        "Mutual pleasure and satisfaction are paramount to me in a sexual encounter; I believe both partners should feel fulfilled and valued.",
        "Ensuring mutual pleasure and satisfaction is a top priority for me; it creates a more enjoyable and fulfilling experience for both partners.",
        "I place a high importance on mutual pleasure and satisfaction in a sexual encounter; it fosters a deeper connection and intimacy between partners.",
        "Mutual pleasure and satisfaction are essential for me; I believe both partners should actively participate in ensuring each other's enjoyment.",
        "I prioritize mutual pleasure and satisfaction in a sexual encounter; it's the foundation of a healthy and fulfilling sexual relationship.",
        "For me, mutual pleasure and satisfaction are non-negotiable in a sexual encounter; it's essential for building trust and intimacy with my partner.",
        "I believe in prioritizing mutual pleasure and satisfaction in a sexual encounter; it creates a more harmonious and fulfilling dynamic between partners.",
        "Ensuring mutual pleasure and satisfaction is integral to my approach to sex; it's a key component of a mutually respectful and enjoyable encounter.",
        "I value mutual pleasure and satisfaction above all else in a sexual encounter; it's what ultimately leads to a fulfilling and memorable experience.",
        "Mutual pleasure and satisfaction are central to my sexual philosophy; it's about giving and receiving pleasure in equal measure with my partner."
    ),
    listOf(
        "I'm open to exploring different locations or settings for sexual activities; it adds excitement and novelty to the experience.",
        "While privacy and familiarity are important, I'm also intrigued by the idea of exploring different locations for sexual activities; it can reignite passion and spontaneity.",
        "I enjoy the comfort and intimacy of familiar settings for sexual activities, but I'm also curious about exploring new locations with my partner; it adds an element of adventure and thrill.",
        "I appreciate the intimacy of privacy and familiarity in sexual encounters, but I'm open to exploring different locations for added excitement and variety.",
        "I value privacy and familiarity in sexual encounters, but I'm also interested in exploring different settings with my partner; it can enhance the overall experience and deepen our connection.",
        "While I enjoy the comfort of privacy and familiarity, I'm open to exploring different locations for sexual activities with my partner; it keeps things exciting and unpredictable.",
        "I find the idea of exploring different locations for sexual activities to be enticing and adventurous; it adds an element of spontaneity and excitement to the experience.",
        "While privacy and familiarity are important to me, I'm also intrigued by the idea of exploring new locations for sexual activities with my partner; it can reignite passion and desire.",
        "I appreciate the intimacy of privacy and familiarity in sexual encounters, but I'm open to stepping outside of my comfort zone and exploring different locations with my partner.",
        "Exploring different locations for sexual activities can add variety and excitement to the experience; I'm open to trying new things with my partner to keep our relationship dynamic and fulfilling."
    ),
    listOf(
        "I have several specific fantasies and role-playing scenarios I'd like to explore with a partner; they range from adventurous and playful to deeply intimate and passionate.",
        "Fantasies and role-playing scenarios are an exciting part of my sexual repertoire; I have a few specific ones in mind that I'd love to explore with a willing partner.",
        "I'm intrigued by the idea of exploring specific fantasies and role-playing scenarios with a partner; they add an element of excitement and novelty to the sexual experience.",
        "I have a vivid imagination when it comes to fantasies and role-playing scenarios; there are a few specific ones I've been eager to bring to life with a like-minded partner.",
        "Fantasies and role-playing scenarios are a fun and creative way to spice up sexual encounters; I have a few specific ones I've been itching to try with the right person.",
        "I enjoy exploring the realm of fantasy and role-playing in my sexual experiences; I have a few specific scenarios in mind that I'd love to act out with a willing partner.",
        "I have a collection of specific fantasies and role-playing scenarios that I'd like to explore with a partner; they allow for imaginative and adventurous sexual exploration.",
        "Fantasies and role-playing scenarios are an exciting way to add variety and excitement to sexual encounters; I have a few specific ones I'm eager to explore with a compatible partner.",
        "I find that fantasies and role-playing scenarios can enhance the intimacy and excitement of sexual encounters; I have a selection of specific ones I'd like to share and explore with a partner.",
        "I'm drawn to the creativity and spontaneity of fantasies and role-playing scenarios in sexual encounters; I have a list of specific ones I'd like to bring to life with a willing and open-minded partner."
    ),
    listOf(
        "Communication and feedback during sex are crucial for me; they ensure that both partners' needs and desires are understood and fulfilled.",
        "I prioritize communication and feedback during sex; they create a supportive and satisfying environment where both partners feel heard and valued.",
        "Communication and feedback are essential elements of sexual intimacy for me; they promote mutual understanding and enhance the overall experience.",
        "I believe in the importance of communication and feedback during sex; they help build trust and intimacy while ensuring that both partners enjoy themselves.",
        "For me, communication and feedback are fundamental in sexual encounters; they enable partners to express desires and preferences openly, leading to greater satisfaction.",
        "I consider communication and feedback vital for fulfilling sexual experiences; they allow partners to navigate pleasure and comfort collaboratively.",
        "Communication and feedback play a significant role in sexual encounters for me; they promote connection and satisfaction by addressing needs and boundaries.",
        "I value communication and feedback during sex; they contribute to a positive and respectful dynamic where both partners feel comfortable expressing themselves.",
        "Communication and feedback are paramount in ensuring both partners' needs are met during sex; they foster a supportive and enjoyable atmosphere of mutual understanding.",
        "I prioritize communication and feedback in sexual interactions; they contribute to a fulfilling and pleasurable experience by addressing preferences and concerns."
    )
)
val limitsANDBoundariesAnswers = listOf(
    listOf(
        "My hard limits and non-negotiable boundaries include anything involving non-consensual or coercive behavior, as well as activities that pose significant physical or emotional risk.",
        "Absolutely, I prioritize open communication and mutual respect for each other's boundaries during sexual encounters.",
        "Consent and mutual agreement are paramount to me; they form the foundation of any healthy and respectful sexual interaction.",
        "Yes, I believe establishing safe words or signals is important for ensuring clear communication and maintaining a safe and consensual environment during sex.",
        "I'm completely open to discussing my sexual health status and practices with potential partners; honesty and transparency are key.",
        "I approach such situations with honesty and respect, communicating my boundaries clearly while also being receptive to my partner's perspective.",
        "Yes, I always prioritize using protection and practicing safe sex with new partners to ensure both our health and well-being.",
        "I have specific preferences and standards regarding sexual hygiene and cleanliness, and I appreciate partners who share similar values.",
        "I navigate discussions about safer sex practices and STI testing with potential partners openly and non-judgmentally, emphasizing the importance of mutual responsibility.",
        "Yes, I'm open to discussing past sexual experiences or history with new partners, as long as it contributes to building trust and understanding between us."
    ),
    listOf(
        "Absolutely, I prioritize open communication and mutual respect for each other's boundaries during sexual encounters.",
        "Yes, I believe that understanding and respecting my partner's boundaries is essential for creating a safe and enjoyable experience for both of us.",
        "Respecting my partner's boundaries is a top priority for me; it's crucial for building trust and intimacy in any sexual interaction.",
        "Without a doubt, I'm comfortable discussing and honoring my partner's boundaries during sex; it's a fundamental aspect of mutual respect and consent.",
        "I value my partner's comfort and boundaries above all else, and I'm committed to ensuring that they feel safe and respected during sexual encounters.",
        "Discussing and respecting my partner's boundaries is non-negotiable for me; it's a fundamental part of fostering trust and mutual understanding in any relationship.",
        "Yes, I'm completely comfortable with discussing and adhering to my partner's boundaries during sexual encounters; it's an essential aspect of consent and mutual respect.",
        "Absolutely, I believe that open communication about boundaries is essential for creating a positive and fulfilling sexual experience for both partners.",
        "I make it a priority to have open and honest conversations about boundaries with my partner, and I'm committed to respecting their limits and preferences.",
        "Respecting my partner's boundaries is not only important but essential for building a healthy and consensual sexual relationship; it's something I take very seriously."
    ),
    listOf(
        "Consent and mutual agreement are paramount to me; they form the foundation of any healthy and respectful sexual interaction.",
        "Without consent and mutual agreement, any sexual activity is unacceptable to me; it's a non-negotiable aspect of sexual encounters.",
        "I cannot overstate the importance of consent and mutual agreement before engaging in any sexual activity; it's an absolute prerequisite for me.",
        "For me, consent and mutual agreement are not just important but fundamental aspects of sexual encounters; there are no exceptions.",
        "Consent and mutual agreement are the cornerstone of any healthy sexual relationship, and I prioritize them above all else.",
        "Establishing clear consent and mutual agreement before engaging in any sexual activity is essential for me; it's a matter of respect and integrity.",
        "Consent and mutual agreement are non-negotiable for me; I cannot engage in any sexual activity without them.",
        "I firmly believe that sexual activity without clear consent and mutual agreement is not only unacceptable but harmful; it's something I take very seriously.",
        "Consent and mutual agreement are vital components of any sexual encounter, and I am committed to upholding them in all my interactions.",
        "I consider consent and mutual agreement to be absolute prerequisites for engaging in any sexual activity; there are no exceptions or compromises."
    ),
    listOf(
        "Yes, I prefer to establish safe words or signals with my partner to communicate discomfort or the need to stop during sex; it's a crucial aspect of ensuring safety and consent.",
        "Absolutely, I believe that safe words or signals are essential for creating a safe and consensual environment during sex; they provide a clear way to communicate boundaries and discomfort.",
        "Establishing safe words or signals is important to me; they allow for open and honest communication during sex, ensuring that both partners feel comfortable and respected.",
        "Yes, I prefer to use safe words or signals during sex to communicate discomfort or the need to stop; it's a proactive measure that promotes safety and mutual understanding.",
        "I believe that using safe words or signals is an important part of sexual encounters; they provide a way to express boundaries and ensure that both partners are on the same page.",
        "I'm a firm believer in using safe words or signals during sex to communicate discomfort or the need to stop; it's a simple yet effective way to prioritize consent and safety.",
        "Yes, I always establish safe words or signals with my partner before engaging in any sexual activity; it's a vital aspect of ensuring clear communication and mutual respect.",
        "Using safe words or signals is non-negotiable for me; they are an essential tool for maintaining a safe and consensual environment during sex.",
        "Absolutely, I believe that safe words or signals play a crucial role in sexual encounters; they provide a means for partners to communicate boundaries and ensure that both feel safe and respected.",
        "Yes, I prefer to establish safe words or signals with my partner to ensure that we can communicate openly and honestly during sex, prioritizing each other's comfort and well-being."
    ),
    listOf(
        "Yes, I am open to discussing my sexual health status and practices with potential partners; I believe it's essential for fostering trust and transparency in any sexual relationship.",
        "Absolutely, I think it's crucial to have open and honest conversations about sexual health with potential partners; it demonstrates a commitment to mutual well-being and safety.",
        "I prioritize discussing my sexual health status and practices with potential partners; it's a responsible and respectful approach to sexual relationships.",
        "Yes, I am completely open to discussing my sexual health status and practices with potential partners; it's an important aspect of building trust and ensuring mutual respect.",
        "Discussing sexual health is a non-negotiable aspect of any potential sexual relationship for me; it's essential for promoting safety and well-being.",
        "I believe in being open and transparent about my sexual health status and practices with potential partners; it's a sign of maturity and responsibility.",
        "Yes, I am comfortable discussing my sexual health status and practices with potential partners; it's an important conversation to have for the sake of mutual understanding and trust.",
        "Absolutely, I think it's important to have open and honest discussions about sexual health with potential partners; it helps create a safe and respectful environment for all parties involved.",
        "I am fully open to discussing my sexual health status and practices with potential partners; it's a necessary step towards building a healthy and fulfilling sexual relationship.",
        "Yes, I believe in having open and candid conversations about sexual health with potential partners; it's a fundamental aspect of responsible sexual behavior."
    ),
    listOf(
        "I approach such situations with honesty and respect, expressing my boundaries calmly and clearly while also being understanding of my partner's desires.",
        "When faced with such a situation, I communicate my feelings openly and respectfully, emphasizing the importance of mutual comfort and consent.",
        "I prioritize open and honest communication in such situations, expressing my concerns and boundaries while also listening to my partner's perspective with empathy and understanding.",
        "I handle such situations by respectfully expressing my discomfort and boundaries, reassuring my partner that it's nothing personal while also being firm in my stance.",
        "In such situations, I engage in a constructive dialogue with my partner, seeking to understand their perspective while also articulating my own boundaries and limitations.",
        "I approach such situations with empathy and understanding, acknowledging my partner's desires while also asserting my own boundaries with clarity and respect.",
        "When confronted with such a situation, I communicate my boundaries assertively but compassionately, emphasizing the importance of mutual respect and consent.",
        "I handle such situations by initiating an open and honest conversation with my partner, expressing my feelings and concerns while also actively listening to their perspective.",
        "In such situations, I prioritize mutual respect and understanding, engaging in a candid discussion with my partner to find a mutually agreeable solution.",
        "When faced with a situation where my partner wants to try something I'm not comfortable with, I communicate my boundaries assertively and respectfully, ensuring that both of our needs and desires are acknowledged and respected."
    ),
    listOf(
        "Yes, I prioritize protection and practicing safe sex with new partners; it's a non-negotiable aspect of sexual health and well-being for me.",
        "Absolutely, I am comfortable using protection and practicing safe sex with new partners; it's essential for mutual respect and responsibility.",
        "I am fully committed to using protection and practicing safe sex with new partners; it's a fundamental aspect of maintaining sexual health and safety.",
        "Yes, I am comfortable using protection and practicing safe sex with new partners; it's an important part of fostering trust and mutual well-being.",
        "I prioritize protection and practicing safe sex with new partners as a way to ensure both parties' safety and well-being.",
        "Absolutely, I am committed to using protection and practicing safe sex with new partners; it's a responsible approach to sexual health.",
        "Yes, I prioritize protection and practicing safe sex with new partners; it's a sign of respect and consideration for both parties involved.",
        "I am fully comfortable using protection and practicing safe sex with new partners; it's a necessary step towards maintaining sexual health and well-being.",
        "Absolutely, I am committed to using protection and practicing safe sex with new partners; it's an essential aspect of responsible sexual behavior.",
        "Yes, I prioritize protection and practicing safe sex with new partners; it's a crucial aspect of maintaining sexual health and mutual respect."
    ),
    listOf(
        "Yes, I have specific preferences and requirements regarding sexual hygiene and cleanliness, and I am comfortable discussing them with potential partners.",
        "Absolutely, I have certain preferences and requirements regarding sexual hygiene and cleanliness, and I am open to discussing them with potential partners.",
        "I have specific preferences and requirements regarding sexual hygiene and cleanliness, and I am committed to discussing them openly and honestly with potential partners.",
        "Yes, I prioritize sexual hygiene and cleanliness, and I am comfortable discussing my preferences and requirements with potential partners.",
        "Absolutely, I have clear preferences and requirements regarding sexual hygiene and cleanliness, and I am willing to communicate them openly and respectfully with potential partners.",
        "I am comfortable discussing my preferences and requirements regarding sexual hygiene and cleanliness with potential partners, as it is important for mutual respect and comfort.",
        "Yes, I have specific preferences and requirements regarding sexual hygiene and cleanliness, and I am open to discussing them with potential partners to ensure a mutually enjoyable experience.",
        "I prioritize sexual hygiene and cleanliness, and I am comfortable communicating my preferences and requirements with potential partners to maintain a healthy and respectful dynamic.",
        "Absolutely, I have certain preferences and requirements regarding sexual hygiene and cleanliness, and I am committed to discussing them openly and constructively with potential partners.",
        "Yes, I have clear preferences and requirements regarding sexual hygiene and cleanliness, and I am open to discussing them with potential partners to establish mutual understanding and comfort."
    ),
    listOf(
        "I approach discussions about safer sex practices and STI testing with potential partners openly and honestly, emphasizing the importance of mutual trust and responsibility.",
        "I initiate discussions about safer sex practices and STI testing with potential partners in a respectful and non-judgmental manner, prioritizing open communication and mutual understanding.",
        "I navigate discussions about safer sex practices and STI testing with potential partners by initiating a candid and transparent conversation, ensuring that both parties' concerns and preferences are acknowledged and addressed.",
        "I approach discussions about safer sex practices and STI testing with potential partners with empathy and understanding, recognizing the importance of mutual respect and consideration.",
        "I engage in open and honest discussions about safer sex practices and STI testing with potential partners, emphasizing the need for mutual responsibility and well-being.",
        "I initiate discussions about safer sex practices and STI testing with potential partners in a compassionate and understanding manner, fostering an environment of trust and transparency.",
        "I approach discussions about safer sex practices and STI testing with potential partners proactively, prioritizing mutual respect and well-being.",
        "I navigate discussions about safer sex practices and STI testing with potential partners by initiating an open and transparent dialogue, ensuring that both parties feel comfortable expressing their concerns and preferences.",
        "I approach discussions about safer sex practices and STI testing with potential partners with openness and honesty, fostering a supportive and understanding atmosphere.",
        "I engage in discussions about safer sex practices and STI testing with potential partners in a respectful and considerate manner, prioritizing the well-being and comfort of both parties."
    ),
    listOf(
        "Yes, I am open to discussing past sexual experiences or history with new partners, as I believe it's important for building trust and understanding in a relationship.",
        "Absolutely, I am comfortable discussing past sexual experiences or history with new partners, as it can help foster open communication and connection.",
        "I am fully open to discussing past sexual experiences or history with new partners, as I believe it's an integral part of getting to know each other on a deeper level.",
        "Yes, I prioritize open and honest communication about past sexual experiences or history with new partners, as it can strengthen the foundation of a relationship.",
        "Absolutely, I am comfortable discussing past sexual experiences or history with new partners, as it allows for greater intimacy and connection.",
        "I am fully open to discussing past sexual experiences or history with new partners, as I believe it's important to be transparent and authentic in a relationship.",
        "Yes, I am open to discussing past sexual experiences or history with new partners, as it can help establish trust and mutual understanding.",
        "Absolutely, I am comfortable discussing past sexual experiences or history with new partners, as it promotes vulnerability and emotional intimacy.",
        "I am fully open to discussing past sexual experiences or history with new partners, as I believe it's an essential part of building a strong and healthy relationship.",
        "Yes, I prioritize open and honest communication about past sexual experiences or history with new partners, as it lays the groundwork for a trusting and fulfilling connection."
    )
)
val expectationsANDCommunicationAnswers = listOf(
    listOf(
        "Openly and directly, ensuring both needs are met and respected.",
        "Yes, fostering a safe and judgment-free space for exploration.",
        "Approach with honesty, empathy, and willingness to address concerns.",
        "Absolutely, key to mutual satisfaction and pleasure.",
        "Very important to ensure both partners are on the same page.",
        "Yes, transparency is essential for building trust and intimacy.",
        "With sensitivity, respect, and a willingness to understand.",
        "Approaching with sensitivity, respect, and a willingness to listen.",
        "Prioritizing open communication, empathy, and finding common ground.",
        "Actively listening, communicating openly, and prioritizing comfort and well-being."
    ),
    listOf(
        "Yes, I believe in open-mindedness and exploring desires without judgment.",
        "Absolutely, it's crucial for building trust and intimacy.",
        "I'm comfortable discussing all aspects of sexuality in a safe and respectful environment.",
        "Yes, I think it's important to be open and honest about all aspects of sexual desires.",
        "Absolutely, as long as there's mutual respect and understanding.",
        "Yes, I believe in embracing all facets of human sexuality.",
        "Definitely, exploring fantasies and desires can lead to deeper connection and fulfillment.",
        "Yes, it's essential for fostering intimacy and understanding between partners.",
        "Absolutely, I think it's healthy to discuss all aspects of sexuality with a partner.",
        "Yes, it's important to create a space where all desires are welcome and respected."
    ),
    listOf(
        "Approach with sensitivity and openness, prioritizing mutual satisfaction and growth.",
        "Yes, feedback is crucial for improving the sexual experience and ensuring both partners are fulfilled.",
        "I believe in open and honest communication to address any concerns or areas for improvement.",
        "Absolutely, it's important to create a safe space for open dialogue and feedback.",
        "With honesty and empathy, focusing on mutual pleasure and satisfaction.",
        "Yes, constructive feedback is essential for enhancing the sexual experience and deepening intimacy.",
        "I prioritize creating a supportive environment where both partners feel comfortable expressing their needs.",
        "Definitely, feedback is essential for growth and mutual satisfaction in the bedroom.",
        "I approach these conversations with care and understanding, emphasizing mutual pleasure and connection.",
        "Yes, I'm open to feedback and believe it's necessary for a fulfilling sexual relationship."
    ),
    listOf(
        "Absolutely, feedback is essential for mutual satisfaction and growth in the relationship.",
        "Yes, I believe open communication leads to a deeper connection and better sexual experiences.",
        "I'm open to feedback and see it as an opportunity to improve and better understand my partner's needs.",
        "Definitely, creating a safe space for feedback fosters trust and enhances the overall experience.",
        "Yes, I value honest communication and see it as a way to strengthen intimacy.",
        "I believe feedback is crucial for understanding and meeting each other's desires and needs.",
        "Absolutely, mutual feedback ensures both partners are fully satisfied and fulfilled.",
        "Yes, I see giving and receiving feedback as a way to deepen intimacy and improve sexual connection.",
        "I'm open to feedback and see it as an essential part of sexual exploration and growth.",
        "Yes, I believe in constant communication and improvement to ensure both partners are satisfied."
    ),
    listOf(
        "Open and honest communication is crucial for establishing mutual understanding and respect.",
        "Yes, addressing concerns and anxieties beforehand ensures a safe and enjoyable experience for both.",
        "I believe clear communication fosters trust and allows both partners to feel comfortable and respected.",
        "Absolutely, discussing preferences and expectations beforehand sets the stage for a fulfilling encounter.",
        "Yes, addressing concerns and anxieties promotes a sense of trust and intimacy between partners.",
        "I prioritize open communication to ensure both partners' needs and boundaries are respected.",
        "I believe discussing sexual preferences and expectations beforehand leads to a more satisfying encounter.",
        "Yes, open communication is key to building trust and ensuring a positive sexual experience.",
        "Clear communication about concerns and anxieties allows for a more enjoyable and consensual encounter.",
        "I consider open communication about sexual preferences and expectations essential for a fulfilling encounter."
    ),
    listOf(
        "Absolutely, open dialogue about concerns and anxieties is vital for a mutually satisfying experience.",
        "Yes, discussing concerns and anxieties fosters trust and enhances intimacy in the relationship.",
        "I believe in open communication to address any concerns or anxieties and ensure a positive experience.",
        "Definitely, I value honesty and transparency in discussing any apprehensions or worries.",
        "Yes, I prioritize open communication to ensure both partners feel comfortable and respected.",
        "Absolutely, discussing concerns and anxieties beforehand helps create a safe and enjoyable environment.",
        "Yes, I'm comfortable expressing any concerns or anxieties to ensure a mutually satisfying encounter.",
        "I believe in open dialogue to address any concerns or anxieties and foster understanding between partners.",
        "Yes, open communication allows for a deeper connection and ensures both partners' needs are met.",
        "Definitely, I see discussing concerns and anxieties as an essential part of building trust and intimacy."
    ),
    listOf(
        "I approach discussions about sexual history with honesty, respect, and sensitivity.",
        "Open communication is key; I strive to listen attentively and share my own experiences with transparency.",
        "I believe in creating a non-judgmental space where both partners feel comfortable sharing their sexual history.",
        "I navigate discussions about sexual history with empathy and understanding, prioritizing mutual respect.",
        "I approach conversations about sexual history with curiosity and a willingness to listen and learn from my partner.",
        "I believe in discussing sexual history openly and respectfully, recognizing that everyone's experiences are unique.",
        "I navigate discussions about sexual history with an open mind and a commitment to mutual understanding.",
        "I approach conversations about sexual history with sensitivity and a focus on building trust and intimacy.",
        "I strive to create a supportive environment where both partners feel comfortable sharing their sexual experiences.",
        "Open and honest communication is essential; I navigate discussions about sexual history with empathy and care."
    ),
    listOf(
        "I am open to discussing boundaries and expectations to ensure that both partners are on the same page.",
        "Yes, I believe it's important to establish clear boundaries and expectations to avoid misunderstandings.",
        "I am open to discussing the nature of the sexual encounter and am willing to respect my partner's preferences.",
        "Absolutely, I think it's crucial to have open and honest conversations about what each partner is looking for.",
        "Yes, I am open to discussing the nature of the encounter and am committed to mutual understanding and respect.",
        "I believe in having transparent conversations about boundaries and expectations to ensure a positive experience for both parties.",
        "I am open to discussing boundaries and expectations and am committed to creating a safe and consensual environment.",
        "Yes, I am open to discussing the nature of the encounter and am willing to adapt to my partner's needs and desires.",
        "I believe in open communication and am willing to discuss boundaries and expectations to ensure a mutually satisfying experience.",
        "Absolutely, I am open to discussing boundaries and expectations and believe it's essential for a healthy sexual encounter."
    ),
    listOf(
        "I believe in open communication and would discuss our differences to find a mutually satisfying solution.",
        "I would approach the situation with empathy and understanding, seeking to find common ground with my partner.",
        "I would prioritize honest communication and actively listen to my partner's perspective to address any mismatches.",
        "I believe in finding compromises and solutions that respect both partners' needs and boundaries.",
        "I would strive to understand my partner's perspective and work together to find a resolution that respects both of our desires.",
        "I would initiate a respectful conversation to understand my partner's needs better and find a way to bridge the gap.",
        "I believe in finding a middle ground that honors both partners' desires and fosters mutual satisfaction.",
        "I would approach the situation with patience and empathy, seeking to find a solution that works for both of us.",
        "I would prioritize open communication and mutual respect, aiming to find a resolution that honors both partners' needs.",
        "I believe in addressing any mismatches in desires or expectations through open dialogue and mutual understanding."
    ),
    listOf(
        "I prioritize clear communication and actively listen to my partner's needs and boundaries.",
        "I ensure that consent is always present and respect any boundaries my partner communicates.",
        "I take cues from my partner's body language and verbal cues to ensure their comfort and enjoyment.",
        "I prioritize creating a safe and comfortable environment where my partner feels empowered to express their needs.",
        "I check in with my partner regularly to ensure their comfort and adjust accordingly.",
        "I prioritize mutual pleasure and satisfaction, ensuring that both partners' needs are met.",
        "I respect my partner's autonomy and empower them to communicate their desires and boundaries without judgment.",
        "I prioritize building trust and emotional connection, which fosters open communication and respect for boundaries.",
        "I am attentive to my partner's reactions and adjust my actions accordingly to ensure their comfort and pleasure.",
        "I believe in mutual respect and understanding, valuing my partner's feelings and boundaries as much as my own."
    ),
)